services:
    contactinformation.model:
            class:        BiberLtd\Bundle\ContactInformationBundle\Services\ContactInformationModel
            arguments:    ["@kernel", "default", "doctrine"]